export const pageActivity = {
    GetPageItem : 1,
    DecryptPageItem : 2,
    SaveTags : 4,
    SaveTitle : 8,
    SaveContent : 16,
    UploadImages : 32,
    DeleteAnImage : 64,
    UploadAttachments : 128,
    DeleteAnAttachment : 256,
    SaveImageWords : 512,
    SaveComment : 1 *1024,
    LoadComments : 2 *1024,
    GetVersionsHistory : 4 *1024,
} 