import { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux'
import Head from 'next/head'
import Button from 'react-bootstrap/Button' 
import BSafesStyle from '../styles/BSafes.module.css'
import ContentPageLayout from '../components/layouts/contentPageLayout';

import jquery from "jquery"

import Scripts from '../components/scripts'
import ImagesGallery from '../components/imagesGallery';

export default function Home() {

  const scriptsLoaded = useSelector(state => state.scripts.done);

  useEffect(() => {
    window.$ = window.jQuery = jquery;
    if(scriptsLoaded) {
      $("#edit").froalaEditor();
    }
  },[scriptsLoaded])

  const upload = async () => {
    $.get("/", function(data, status){
      console.log("Data: " + data + "\nStatus: " + status);
    });
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContentPageLayout>
        <main>
          <h1>Introduction</h1>

          <div id='edit'></div>
        
          <ImagesGallery />
        </main>
      </ContentPageLayout>

      <footer>

      </footer>
      <Scripts />
    </div>
  )
}
