import Head from 'next/head'

import ContentPageLayout from '../components/layouts/contentPageLayout';

import Scripts from '../components/scripts'

export default function Home() {
  const debugOn = false;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContentPageLayout>
        Hello
      </ContentPageLayout>

      <footer>

      </footer>

    </div>
  )
}
