import { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux'
import Head from 'next/head'
import BSafesStyle from '../styles/BSafes.module.css'
import ContentPageLayout from '../components/layouts/contentPageLayout';

import jquery from "jquery"

import Scripts from '../components/scripts'

export default function Home() {

  const scriptsLoaded = useSelector(state => state.scripts.done);

  useEffect(() => {
    window.$ = window.jQuery = jquery;
    if(scriptsLoaded) {
      $("#edit").froalaEditor();
    }
  },[scriptsLoaded])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ContentPageLayout>
        <main>
          <h1>Introduction</h1>

          <div id='edit'></div>
        </main>
      </ContentPageLayout>

      <footer>

      </footer>
      <Scripts />
    </div>
  )
}
